<h2>
    商品情報を入力してください
</h2>

<?php echo $this->tag->form("signup/register"); ?>

    <p>
        <label for="name">
            商品タイトル
        </label>
<input type="text" name="name" maxlength="100" size="50">
    </p>

    <p>
        <label for="exp">
            説明文
        </label>
<textarea name="exp" maxlength="500" cols="50" rows="5"></textarea>
    </p>

    <p>
        <label for="price">
            価格
        </label>
<input type="text" name="price" maxlength="100" size="50">
    </p>

    <p>
        <?php echo $this->tag->submitButton("登録"); ?>
    </p>

</form>